version: '3'
services:
  backend:
    image: backend-image
    ports:
      - 8080:8080
    networks:
      - app-network

  frontend:
    image: frontend-image
    ports:
      - 80:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
